##----------kubelet 配置部分--------------
- name: 下载 kubelet二进制
  copy: src={{ base_dir }}/bin/kubernetes/kubelet dest={{ bin_dir }}/kubelet mode=0755
  
- name: 下载基础 cni plugins
  copy: src={{ base_dir }}/bin/cni/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - bridge
  - host-local
  - loopback

- name: 关闭swap
  shell: swapoff -a && grep "swappiness" /etc/sysctl.conf ; if [ $? -eq 0 ];then { sed -i "s/vm.swap.*$/vm.swappiness = 0/g" /etc/sysctl.conf; } else { echo "vm.swappiness = 0" >> /etc/sysctl.conf; } fi && sed -i '/swap/d' /etc/fstab

##----------kubelet 配置部分--------------
#master\lb节点 kubelet 启动所需的kubeconfig文件
- block:
  - name: 创建kubelet-csr.json文件
    template: src=kubelet-csr.json.j2 dest={{ ca_dir }}/kubelet-csr.json
  
  - name: 创建kubelet密钥
    shell: "{{cfssl_cmd }} 'cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -hostname={{ inventory_hostname }},{{ MASTER_IP }} \
      -profile=kubernetes \
      kubelet-csr.json | cfssljson -bare kubelet'"
    
  - name: 创建kubelet.kubeconfig文件
    shell: "{{ bin_dir }}/kubectl config set-cluster kubernetes \
      --certificate-authority={{ ca_dir }}/ca.pem \
      --embed-certs=true \
      --server=https://{{ MASTER_IP }}:{{MASTER_PORT}} \
      --kubeconfig=/etc/kubernetes/kubelet.kubeconfig"
  
  - name: kubelet.kubeconfig设置客户端证书
    shell: "{{ bin_dir }}/kubectl config set-credentials system:node:{{NODE_ID}} \
      --client-certificate={{ ca_dir }}/kubelet.pem \
      --client-key={{ ca_dir }}/kubelet-key.pem \
      --embed-certs=true \
      --kubeconfig=/etc/kubernetes/kubelet.kubeconfig"
  
  - name: kubelet.kubeconfig设置用户
    shell: "{{ bin_dir }}/kubectl config set-context system:node:{{NODE_ID}}@kubernetes \
      --cluster=kubernetes \
      --user=system:node:{{NODE_ID}} \
      --kubeconfig=/etc/kubernetes/kubelet.kubeconfig"
  
  - name: kubelet.kubeconfig设置上下文
    shell: "{{ bin_dir}}/kubectl config use-context system:node:{{NODE_ID}}@kubernetes \
      --kubeconfig=/etc/kubernetes/kubelet.kubeconfig"
  when: "kube-master" in group_names or "lb" in group_names
  
#计算节点则创建bootstrap.kubeconfig文件
- name: 安装bootstrap.kubeconfig配置文件
  copy: src=/etc/kubernetes/bootstrap.kubeconfig dest=/etc/kubernetes/bootstrap.kubeconfig
  when: "kube-master" not in group_names and "lb" not in group_names

#准备kubelet服务
- name: 创建kubelet的工作目录
  file: name=/data/kubelet state=directory

- name: 创建kubelet的systemd unit文件
  template: src=kubelet.service.j2 dest=/etc/systemd/system/kubelet.service
  tags: upgrade_k8s
  
- name: 创建kubelet的配置文件
  template: src=kubelet-config.yaml.j2 dest={{kubelet_dir}}/config.yaml
  tags: upgrade_k8s

# kubelet 启动时向 kube-apiserver 发送 TLS bootstrapping 请求，需要绑定该角色
# 只需单节点执行一次
- block:
  - name: 等待master节点启动
    shell: while true; do status=`curl http://{{ MASTER_IP }}:{{ MASTER_INSECURE_PORT }}/healthz`;if [ "${status}" = "ok" ];then break;else sleep 3;fi done
    
  - name: kubelet-bootstrap-setting
    shell: "{{ bin_dir }}/kubectl apply -f {{base_dir}}/roles/kubernetes/kube-node/files/kubelet-bootstrap.yaml"
    delegate_to: localhost
    run_once: true
    
# 配置证书自动续期
  - name: kubelet-cert-renew-setting
    shell: "{{ bin_dir }}/kubectl apply -f {{base_dir}}/roles/kubernetes/kube-node/files/controller-manager-auto-appove.yaml"
    delegate_to: localhost
    run_once: true
  when: '"kube-node" in group_names and not ansible_check_mode'
  
- name: restart service kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
    enabled: yes
  tags: upgrade_k8s

- block:
  # 批准 node 节点，首先轮询等待kubelet启动完成
  - name: 轮询等待kubelet启动
    shell: "systemctl status kubelet.service|grep Active"
    register: kubelet_status
    until: '"running" in kubelet_status.stdout'
    retries: 8
    delay: 2
    when: not ansible_check_mode
  
  - name: 获取csr 请求信息
    shell: "sleep 3 && {{ bin_dir }}/kubectl get csr"
    register: csr_info
    run_once: true
  
  - name: approve-kubelet-csr
    shell: "{{ bin_dir }}/kubectl get csr|grep 'Pending' | awk 'NR>0{print $1}'| \
          xargs {{ bin_dir }}/kubectl certificate approve"
    when: '"Pending" in csr_info.stdout'
    ignore_errors: true
    run_once: true
  when: “kube-node" in group_names

- block:
  - name: 安装nfs客户端
    yum: name={{ item }} state=present
    with_items:
    - nfs-utils
    - rpcbind
    when: storage_type == "nfs"
    
  - name: 启动nfs客户端
    shell: systemctl enable nfs-utils rpcbind && systemctl restart nfs-utils rpcbind
    when: storage_type == "nfs"
    
  - name: 下载 glusterfs rpm包
    copy: src={{ base_dir }}/bin/glusterfs dest={{data_dir}}/rpm mode=0755
    when: ansible_distribution == "CentOS"
    
  - name: glusterfs客户端离线安装
    shell: rpm -i --force {{data_dir}}/rpm/glusterfs/*.rpm
    when: storage_type == "glusterfs" and deploy_offline and ansible_distribution == "CentOS"
    tags:
    - glusterfs
    
  - name: glusterfs客户端在线安装
    yum: name={{ item }} state=present
    with_items:
    - centos-release-gluster7
    when: storage_type == "glusterfs" and not deploy_offline and ansible_distribution == "CentOS"
    
  - name: glusterfs客户端在线安装
    yum: name={{ item }} state=present
    with_items:
    - glusterfs
    - glusterfs-fuse
    when: storage_type == "glusterfs" and not deploy_offline and ansible_distribution == "CentOS"
  when: "lb" not in group_names
  
##-------日志清理部分------------------------------------
- name: master日志清理
  copy: src=logmgr-master.sh dest=/etc/cron.daily/logmgr-master.sh mode=0755
  when: "kube-master" in group_names
- name: 非master日志清理
  copy: src=logmgr-node.sh dest=/etc/cron.daily/logmgr-node.sh mode=0755
  when: "kube-master" not in group_names
#--------------------------------------------------------------
